travis:
  secure:
    BINSTAR_TOKEN: WX1MyRmW9fev0YWLidaJJBmAz/rKgbUQLfRsbEb4z4T9jqQaXIOLICEbJ9nDLg+00UjAtHlR/OQ1K8DB4SP9IyIRezMFjCRtx33qWvaLJHACdKSoOiJyhg5oCeq9wgV7nrMnpDcZUngbZX2ZUTOcgLlb9P/wF8n+LhPxkZPfnr+1lrHJBLZg1E0feKoBxND9Bd1pnn2b/+t6OcGQsN0NMnYFTUkqski6bjPccYM5Kbk1zZM2Vw9wa78P6AwcW/5vFFs7qL+pNp7/Mek+nE1T8+dHM4EkKVLpKem4sncZxEofqo4fdlMEMUIazqjWfUTG/JHBVQXVAZNCyNBwj0OQwLToxnnL74b2qYaJ1I9qsqV8J7ZtCryp3YXK3nqjADvyg6NSmc0azSYnROvYDk1wheMJWESqhGzMTQDSBC/fsK751nP9/oqpFJ+6pNUnTOe1lIZdRCoM16dKB+jQ/L7mBtApTrHSWPnh29BZHwNGLliuu0ezy64DMcHJ5v3FjO5ecvFAeTEAjGshudyp6ZQeEerzsOX3lLYjcQxcSGNOszMnWhMSoxL6YnD148FHxyiLlC3KKArSIQMF+Auz+fSv+tZXcLqBjohZHUkygI2QtuFIXXH2XJmXJKzVa6nz2HD5cZ9Yh5C2vSq3Pp4iKTEDRCMdVJl1twKHNYVeYulUw9M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
