travis:
  secure:
    BINSTAR_TOKEN: aNILuXt+zlLDKppRuxl6eJUFLq+KRr1YLSoAb+EhExheyaASYtfinNpJrCtC9587l3q8ce7WSDwU9/xnHUF1a14LmsgdYklAHHYGtGVkGqu+XfKFP1+jOGUbcWsjkr86/IScG4tAqMwKWYsdn/3JIPlyRMXbJcd1X7KaVvXWdfpgWJA3SqgdAJByOfyc0hy9GXQbPTuq+PesZAYohWWfuTLzEcnCPjVdZ3VQQhePUxLYfugu9HhN0lkuIsyBRRa9jcB8x0RhPchUAh6dVy92BExIPEwNp0RTWONRDfXcE+0cYPDKpZHffArtnAWqa8HcDGf9YijSgBF4rklYDqOszYV7vIUGAcZAhkldkEknonvs0aCspEpglRcRtDe2K5zK+4BWV8oN0lqr2rXdfVF5Zcb2hT5/uxhx6GeJpddgw+q/0b7VzwEqq2qpn2nOXZ5avDFlmspuCwBUP+q6cXXyhLflx2qlpHt84ukVE2vcpaDZ9+Nixhkgqk52o0GpuNuvocNZWOaFHzGHnVMpq3YD+4JVnEVHVCovS52gHb9/mIX/fCjc9R9E6SNyaTxXAwfrKrYn2NckJquYA4jdWlWz94yc8H/IAfS+WdLbJDemsFCPnsh39HoEP2CrrLBq5tRbRWdb5B87hC9H16M8my1mpqcwobJxKuZYFz0a2WrHLvE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
